### ISSUE TITLE
New qbank logo for mod_qbank

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-72752#66]
Qbank logo design for the mod_qbank activity aligned with Moodle 4.0

Are we going to have the same logo for mod_qbank or we will change to a different one for Moodle 4.1?

**Comment by lucaboesch** [comment]
We'll need the new monologo.svg and monologo.png files.
I think Yvonne Wolf already had drawn them.

**Comment by safatshahin** [comment]
Hi @lucaboesch 
Thank you for adding the logo. I currently looking at the logo in qbank activity, and it seems broken, can you please have a look and let me if I am missing something? I have checked the repo you added the PR from, nothing seems missing. Please let me know.
Cheers!

**Comment by lucaboesch** [comment]
I will have to build an instance based on this branch. Hang on, @safatshahin .

**Comment by lucaboesch** [comment]
Oh, that's very infortunate, there's four µ characters at the beginning of the monologo.svg source.
I'm going to amend this.
